spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1035703344297-ioan0j2gtbdpaas3olv2cti6akb7ffrr.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google

          github:
            client-id: Ov23li9W8tNNPlYWcCOP
            client-secret: 17e14eccca853ff76e2f9ac3f57c4fa4d58d3918
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub

        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    com.queddeng.oauth2login: DEBUG
